<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The source code</title>
  <link href="../resources/prettify/prettify.css" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="../resources/prettify/prettify.js"></script>
  <style type="text/css">
    .highlight { display: block; background-color: #ddd; }
  </style>
  <script type="text/javascript">
    function highlight() {
      document.getElementById(location.hash.replace(/#/, "")).className = "highlight";
    }
  </script>
</head>
<body onload="prettyPrint(); highlight();">
  <pre class="prettyprint lang-js"><span id='java-lang-ExceptionInInitializerError'>/**@class java.lang.ExceptionInInitializerError
</span>@extends java.lang.LinkageError

 Signals that an unexpected exception has occurred in a static initializer.
 An &lt;code&gt;ExceptionInInitializerError&lt;/code&gt; is thrown to indicate that an
 exception occurred during evaluation of a static initializer or the
 initializer for a static variable.

 &lt;p&gt;As of release 1.4, this exception has been retrofitted to conform to
 the general purpose exception-chaining mechanism.  The &quot;saved throwable
 object&quot; that may be provided at construction time and accessed via
 the {@link #getException}() method is now known as the &lt;i&gt;cause&lt;/i&gt;,
 and may be accessed via the {@link java.lang.Throwable#getCause()} method, as well
 as the aforementioned &quot;legacy method.&quot;

 @author  Frank Yellin
 @since   JDK1.1
*/
var ExceptionInInitializerError = {

<span id='java-lang-ExceptionInInitializerError-method-getException'>/**Returns the exception that occurred during a static initialization that
</span> caused this error to be created.

 &lt;p&gt;This method predates the general-purpose exception chaining facility.
 The {@link java.lang.Throwable#getCause()} method is now the preferred means of
 obtaining this information.
@return {Object {java.lang.Throwable}} the saved throwable object of this
         &lt;code&gt;ExceptionInInitializerError&lt;/code&gt;, or &lt;code&gt;null&lt;/code&gt;
         if this &lt;code&gt;ExceptionInInitializerError&lt;/code&gt; has no saved
         throwable object.
*/
getException : function(  ) {},

<span id='java-lang-ExceptionInInitializerError-method-getCause'>/**Returns the cause of this error (the exception that occurred
</span> during a static initialization that caused this error to be created).
@return {Object {java.lang.Throwable}} the cause of this error or &lt;code&gt;null&lt;/code&gt; if the
          cause is nonexistent or unknown.
@since 1.4
*/
getCause : function(  ) {},


};</pre>
</body>
</html>
