Ext.data.JsonP.java_security_cert_CertStoreException({"tagname":"class","name":"java.security.cert.CertStoreException","autodetected":{},"files":[{"filename":"CertStoreException.js","href":"CertStoreException.html#java-security-cert-CertStoreException"}],"extends":"java.security.GeneralSecurityException","since":"1.4","author":[{"tagname":"author","name":"Sean Mullan","email":null}],"members":[],"alternateClassNames":[],"aliases":{},"id":"class-java.security.cert.CertStoreException","short_doc":"An exception indicating one of a variety of problems retrieving\n certificates and CRLs from a {@code CertStore}. ...","classIcon":"icon-class","superclasses":["java.security.GeneralSecurityException"],"subclasses":[],"mixedInto":[],"mixins":[],"parentMixins":[],"requires":[],"uses":[],"html":"<div><pre class=\"hierarchy\"><h4>Hierarchy</h4><div class='subclass first-child'>java.security.GeneralSecurityException<div class='subclass '><strong>java.security.cert.CertStoreException</strong></div></div><h4>Files</h4><div class='dependency'><a href='source/CertStoreException.html#java-security-cert-CertStoreException' target='_blank'>CertStoreException.js</a></div></pre><div class='doc-contents'><p>An exception indicating one of a variety of problems retrieving\n certificates and CRLs from a {@code CertStore}.\n <p>\n A {@code CertStoreException} provides support for wrapping\n exceptions. The getCause method returns the throwable,\n if any, that caused this exception to be thrown.\n <p>\n <b>Concurrent Access</b>\n <p>\n Unless otherwise specified, the methods defined in this class are not\n thread-safe. Multiple threads that need to access a single\n object concurrently should synchronize amongst themselves and\n provide the necessary locking. Multiple threads each manipulating\n separate objects need not synchronize.</p>\n\n<p> @see CertStore</p>\n        <p>Available since: <b>1.4</b></p>\n</div><div class='members'></div></div>","meta":{}});