<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The source code</title>
  <link href="../resources/prettify/prettify.css" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="../resources/prettify/prettify.js"></script>
  <style type="text/css">
    .highlight { display: block; background-color: #ddd; }
  </style>
  <script type="text/javascript">
    function highlight() {
      document.getElementById(location.hash.replace(/#/, "")).className = "highlight";
    }
  </script>
</head>
<body onload="prettyPrint(); highlight();">
  <pre class="prettyprint lang-js"><span id='java-io-WriteAbortedException'>/**@class java.io.WriteAbortedException
</span>@extends java.io.ObjectStreamException

 Signals that one of the ObjectStreamExceptions was thrown during a
 write operation.  Thrown during a read operation when one of the
 ObjectStreamExceptions was thrown during a write operation.  The
 exception that terminated the write can be found in the detail
 field. The stream is reset to it's initial state and all references
 to objects already deserialized are discarded.

 &lt;p&gt;As of release 1.4, this exception has been retrofitted to conform to
 the general purpose exception-chaining mechanism.  The &quot;exception causing
 the abort&quot; that is provided at construction time and
 accessed via the public {@link #detail} field is now known as the
 &lt;i&gt;cause&lt;/i&gt;, and may be accessed via the {@link Throwable#getCause()}
 method, as well as the aforementioned &quot;legacy field.&quot;

 @author  unascribed
 @since   JDK1.1
*/
var WriteAbortedException = {

<span id='java-io-WriteAbortedException-property-detail'>/** Exception that was caught while writing the ObjectStream.
</span>
 &lt;p&gt;This field predates the general-purpose exception chaining facility.
 The {@link Throwable#getCause()} method is now the preferred means of
 obtaining this information.

 @serial
*/
detail : &quot;null&quot;,
<span id='java-io-WriteAbortedException-method-getMessage'>/**Produce the message and include the message from the nested
</span> exception, if there is one.
*/
getMessage : function(  ) {},

<span id='java-io-WriteAbortedException-method-getCause'>/**Returns the exception that terminated the operation (the &lt;i&gt;cause&lt;/i&gt;).
</span>@return {Object {java.lang.Throwable}} the exception that terminated the operation (the &lt;i&gt;cause&lt;/i&gt;),
          which may be null.
@since 1.4
*/
getCause : function(  ) {},


};</pre>
</body>
</html>
